### ISSUE TITLE
errors keep the bot from working

### ISSUE THREAD

**Issue by Michael9521** [KMKINGMAN/Application-Bot#5]
Hey, I really like your bot. However there are some problems i'm not able to solve myself. At first the bot was crashing with an error "cannot send messages to this user" but I solved it by disabling sending private messages. Now its stopping with another error that I don't really know the cause of. Is there a way to just make it ignore those errors?
ps. discord invite on your profile is expired 
Thanks in advance

<img width="638" alt="Zrzut ekranu 2022-02-17 o 22 24 32" src="https://user-images.githubusercontent.com/99909540/154573938-ee7e9cd8-2b34-47b7-a196-a253bf1cad8a.png">

**Comment by mkurkar** [comment]
Well, this is a beta version of my bot
I need some time to update my bot for free time
Your problem is that the bot cannot find the message to be deleted
You can solve a problem in three different ways
```js
//1
.catch(e=>{})
//2
try{}catch{}
//3 edit source code
```
You can contact me via 
WhatsApp: +962792914245 or via my Discord server: https://discord.gg/kingmandev
